---
trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
  - script: rustup component add clippy
    displayName: Install Clippy
  - script: cargo build --all
    displayName: Cargo build
  - script: cargo clippy --all
    displayName: Cargo clippy