[package]
name = "ipmi-fan-control"
description = "SuperMicro IPMI fan control daemon"
repository = "https://github.com/chenxiaolong/ipmi-fan-control"
readme = "README.md"
license = "GPL-3.0-or-later"
version = "0.3.0"
authors = ["Andrew Gunnerson <andrewgunnerson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8.2"
futures = "0.3.8"
log = "0.4.11"
rexpect = "0.4.0"
serde_json = "1.0.59"
snafu = "0.6.9"
structopt = "0.3.20"
toml = "0.5"

[dependencies.serde]
version = "1.0.117"
features = ["derive"]

[dependencies.tokio]
version = "0.3.4"
features = ["full"]
