[package]
name = "ipmi-fan-control"
description = "SuperMicro IPMI fan control daemon"
repository = "https://github.com/chenxiaolong/ipmi-fan-control"
readme = "README.md"
license = "GPL-3.0-or-later"
version = "0.3.3"
authors = ["Andrew Gunnerson <andrewgunnerson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
futures = "0.3.19"
log = "0.4.14"
rexpect = "0.4.0"
serde_json = "1.0.74"
snafu = "0.7.0"
tokio-stream = "0.1.8"
toml = "0.5.8"

[dependencies.clap]
version = "3.0.7"
features = ["derive"]

[dependencies.serde]
version = "1.0.133"
features = ["derive"]

[dependencies.tokio]
version = "1.15.0"
features = ["full"]
