# Definition of a logical fan zone.
[[zones]]
# IPMI session. If unspecified, the `default` session is used, which runs
# ipmitool with no arguments. Sessions are defined below in the `sessions`
# section.
#session = "default"

# List of IPMI zones to be included in this logical zone.
ipmi_zones = [0]

# Number of seconds to wait between fan update interations. If unspecified, the
# default interval is 1 second.
interval = 5

# IPMI temperature sensors to use. Sensors that don't exist are ignored.
sensors = ["CPU1 Temp"]

# List of steps for mapping temperatures to duty cycles. The temperatures are
# in degrees Celsius and the PWM duty cycles are fan speed percentages. At 0%
# duty cycle, the fans are completely turned off and at 100% duty cycle, the
# fans are at the maximum speed. Be careful using low percentages as the fans
# may stall.
#
# The algorithm follows the rules below:
#
# * If the current temperature is lower than the first step's `temp`, then the
#   first step's `dcycle` is used.
# * If the current temperature is higher than the last step's `temp`, then the
#   last step's `dcycle` is used.
# * If there are no steps, then the duty cycle is set to 100%.
# * Otherwise, the duty cycle is linearly scaled between the step below the
#   current temperature and the step above the current temperature.
#
# Note that these rules mean that having a single step will result in a fixed
# fan speed. Also, the list must be sorted, `temp` must be strictly increasing,
# and `dcycle` must be increasing.
steps = [
    { temp = 30, dcycle = 30 },
    { temp = 70, dcycle = 70 },
]

# More fan zones can be added
#[[zones]]
#ipmi_zones = [1]
#interval = 5
#sensors = ["CPU2 Temp"]
#steps = [
#    { temp = 30, dcycle = 30 },
#    { temp = 70, dcycle = 70 },
#]

# Optional section for defining other ipmitool sessions. This is not needed when
# connecting to the local machine.
#
# The key is the name of the session, which can be any arbitrary non-empty
# string, and the value is the array of arguments to pass to ipmitool.
[sessions]
# Implicit default session for connecting to local IPMI. This runs ipmitool with
# no arguments. If this is changed, it will take effect in any zone that doesn't
# explicitly specify another session.
#"default" = []

# Example of a remote session.
#"remote" = ["-I", "lanplus", "-H", "<host>", "-U", "<username>", "-P", "<password>"]
