---
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build project
    runs-on: ${{ matrix.os }}
    env:
      CARGO_TERM_COLOR: always
    strategy:
      fail-fast: false
      matrix:
        # Once Windows support is complete, windows-latest can be added
        os: [ubuntu-20.04]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Rust LLVM target triple
        id: get_target
        shell: bash
        run: |
          echo -n '::set-output name=name::'
          RUSTC_BOOTSTRAP=1 rustc -Z unstable-options --print target-spec-json \
              | jq -r '."llvm-target"'

      - name: Install clippy
        run: rustup component add clippy

      - name: Run clippy checks in debug mode
        env:
          RUST_BACKTRACE: 1
        run: |
          cargo clippy -- -D warnings

      - name: Build in debug mode
        run: cargo build --verbose

  build_source_packages:
    name: Build source packages
    runs-on: ubuntu-20.04
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build all source packages
        run: |
          sudo apt-get -y update
          sudo apt-get -y install cargo debhelper devscripts dh-exec
          ./dist/build_source_package.sh -t tarball
          ./dist/build_source_package.sh -t srpm
          ./dist/build_source_package.sh -t pkgbuild
          ./dist/build_source_package.sh -t dsc
