---
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build project
    runs-on: ubuntu-22.04
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Rust LLVM target triple
        id: get_target
        shell: bash
        run: |
          echo -n 'name=' >> "${GITHUB_OUTPUT}"
          RUSTC_BOOTSTRAP=1 rustc -Z unstable-options --print target-spec-json \
              | jq -r '."llvm-target"' \
              >> "${GITHUB_OUTPUT}"

      - name: Install clippy
        run: rustup component add clippy

      - name: Install system dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install clang libfreeipmi-dev libipmimonitoring-dev pkg-config

      - name: Run clippy checks in debug mode
        env:
          RUST_BACKTRACE: 1
        run: |
          cargo clippy -- -D warnings

      - name: Build in debug mode
        run: cargo build --verbose

  build_source_packages:
    name: Build source packages
    runs-on: ubuntu-22.04
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build all source packages
        run: |
          sudo apt-get -y update
          sudo apt-get -y install cargo debhelper devscripts dh-exec
          ./dist/build_source_package.py -a
